//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResumeWebSite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesContent
    {
        public int Id { get; set; }
        public Nullable<int> CoursesId { get; set; }
        public string CourseContent { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
