//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResumeWebSite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyProject
    {
        public int Id { get; set; }
        public string projectName { get; set; }
        public string projectContent { get; set; }
        public string Picture { get; set; }
        public string projectLanguage { get; set; }
    }
}
