//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResumeWebSite.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyResumeEntities : DbContext
    {
        public MyResumeEntities()
            : base("name=MyResumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<CoursesContent> CoursesContent { get; set; }
        public virtual DbSet<DatabaseManagement> DatabaseManagement { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<GameTechnology> GameTechnology { get; set; }
        public virtual DbSet<ProgramingLanguage> ProgramingLanguage { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
        public virtual DbSet<SocialMediaTable> SocialMediaTable { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WebTechnology> WebTechnology { get; set; }
        public virtual DbSet<WorkExperiance> WorkExperiance { get; set; }
    }
}
